'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace local.smfr.sersim.sapapp
    
    'CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ZSFR_MM_022_FM_01", [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZSFR_MM_022_FM_01
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ZSFR_MM_008_FM_01OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.BarcodOkuma.My.MySettings.Default.BarcodOkuma_local_smfr_sersim_sapapp_ZSFR_MM_022_FM_01
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ZSFR_MM_008_FM_01Completed As ZSFR_MM_008_FM_01CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:zsfr_mm_008_fm_01:ZSFR_MM_008_FM_01Request"& _ 
            "", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ZSFR_MM_008_FM_01(<System.Xml.Serialization.XmlElementAttribute("ZSFR_MM_008_FM_01", [Namespace]:="urn:sap-com:document:sap:rfc:functions")> ByVal ZSFR_MM_008_FM_011 As ZSFR_MM_008_FM_01) As <System.Xml.Serialization.XmlElementAttribute("ZSFR_MM_008_FM_01Response", [Namespace]:="urn:sap-com:document:sap:rfc:functions")> ZSFR_MM_008_FM_01Response
            Dim results() As Object = Me.Invoke("ZSFR_MM_008_FM_01", New Object() {ZSFR_MM_008_FM_011})
            Return CType(results(0),ZSFR_MM_008_FM_01Response)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ZSFR_MM_008_FM_01Async(ByVal ZSFR_MM_008_FM_011 As ZSFR_MM_008_FM_01)
            Me.ZSFR_MM_008_FM_01Async(ZSFR_MM_008_FM_011, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ZSFR_MM_008_FM_01Async(ByVal ZSFR_MM_008_FM_011 As ZSFR_MM_008_FM_01, ByVal userState As Object)
            If (Me.ZSFR_MM_008_FM_01OperationCompleted Is Nothing) Then
                Me.ZSFR_MM_008_FM_01OperationCompleted = AddressOf Me.OnZSFR_MM_008_FM_01OperationCompleted
            End If
            Me.InvokeAsync("ZSFR_MM_008_FM_01", New Object() {ZSFR_MM_008_FM_011}, Me.ZSFR_MM_008_FM_01OperationCompleted, userState)
        End Sub
        
        Private Sub OnZSFR_MM_008_FM_01OperationCompleted(ByVal arg As Object)
            If (Not (Me.ZSFR_MM_008_FM_01CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ZSFR_MM_008_FM_01Completed(Me, New ZSFR_MM_008_FM_01CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZSFR_MM_008_FM_01
        
        Private iT_ITEMSField() As ZSFR_MM_008_S_02
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property IT_ITEMS() As ZSFR_MM_008_S_02()
            Get
                Return Me.iT_ITEMSField
            End Get
            Set
                Me.iT_ITEMSField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZSFR_MM_008_S_02
        
        Private sERINOField As String
        
        Private aGIRLIKField As String

        Private bANTField As String
        
        Private tARIHField As String

        'Private zAMANField As Date

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SERINO() As String
            Get
                Return Me.sERINOField
            End Get
            Set
                Me.sERINOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property AGIRLIK() As String
            Get
                Return Me.aGIRLIKField
            End Get
            Set
                Me.aGIRLIKField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BANT() As String
            Get
                Return Me.bANTField
            End Get
            Set
                Me.bANTField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TARIH() As String
            Get
                Return Me.tARIHField
            End Get
            Set
                Me.tARIHField = value
            End Set
        End Property

        ''''<remarks/>
        '<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="time")>  _
        'Public Property ZAMAN() As Date
        '    Get
        '        Return Me.zAMANField
        '    End Get
        '    Set
        '        Me.zAMANField = value
        '    End Set
        'End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZSFR_MM_008_S_01
        
        Private zZIDField As String
        
        Private zZAUFNRField As String
        
        Private zZMUSTERI_SIPField As String
        
        Private zZKALEM_NOField As String
        
        Private zZMATNRField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZZID() As String
            Get
                Return Me.zZIDField
            End Get
            Set
                Me.zZIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZZAUFNR() As String
            Get
                Return Me.zZAUFNRField
            End Get
            Set
                Me.zZAUFNRField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZZMUSTERI_SIP() As String
            Get
                Return Me.zZMUSTERI_SIPField
            End Get
            Set
                Me.zZMUSTERI_SIPField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZZKALEM_NO() As String
            Get
                Return Me.zZKALEM_NOField
            End Get
            Set
                Me.zZKALEM_NOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZZMATNR() As String
            Get
                Return Me.zZMATNRField
            End Get
            Set
                Me.zZMATNRField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZSFR_MM_008_FM_01Response
        
        Private eT_IDField() As ZSFR_MM_008_S_01
        
        Private eV_HATAField As String
        
        Private eV_STATUSField As String
        
        Private iT_ITEMSField() As ZSFR_MM_008_S_02
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property ET_ID() As ZSFR_MM_008_S_01()
            Get
                Return Me.eT_IDField
            End Get
            Set
                Me.eT_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EV_HATA() As String
            Get
                Return Me.eV_HATAField
            End Get
            Set
                Me.eV_HATAField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EV_STATUS() As String
            Get
                Return Me.eV_STATUSField
            End Get
            Set
                Me.eV_STATUSField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property IT_ITEMS() As ZSFR_MM_008_S_02()
            Get
                Return Me.iT_ITEMSField
            End Get
            Set
                Me.iT_ITEMSField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")>  _
    Public Delegate Sub ZSFR_MM_008_FM_01CompletedEventHandler(ByVal sender As Object, ByVal e As ZSFR_MM_008_FM_01CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ZSFR_MM_008_FM_01CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ZSFR_MM_008_FM_01Response
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ZSFR_MM_008_FM_01Response)
            End Get
        End Property
    End Class
End Namespace
